"""Added setup_status table

Revision ID: 3143d88e2d7e
Revises: b1a12874ecdf
Create Date: 2024-12-28 18:16:45.689787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3143d88e2d7e'
down_revision: Union[str, None] = 'b1a12874ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_status_id'), 'setup_status', ['id'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO setup_status (id, setup_completed, current_step)
        VALUES (1, false, 1)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_status_id'), table_name='setup_status')
    op.drop_table('setup_status')
    # ### end Alembic commands ###
