"""Added blog table and foreign keys for blogs

Revision ID: b1a12874ecdf
Revises: f15b5844dc69
Create Date: 2024-12-27 15:58:11.440875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a12874ecdf'
down_revision: Union[str, None] = 'f15b5844dc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.add_column('articles', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.add_column('prompts', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'prompts', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_check_logs', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stock_check_logs', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.add_column('stores', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stores', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'blog_id')
    op.drop_constraint(None, 'stock_check_logs', type_='foreignkey')
    op.drop_column('stock_check_logs', 'blog_id')
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_column('prompts', 'blog_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'blog_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'blog_id')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
